[theme]
base = "light"
primaryColor = "#1A5CFF"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#EAF0FF"
textColor = "rgb(31, 41, 55)"
font = "sans serif"

[server]
favicon = "assets/favicon.jpg"